### ISSUE TITLE
Add support for aarch64/ARM64 wheels

### ISSUE THREAD

**Issue by janaknat** [MacPython/scikit-learn-wheels#66]
Travis-CI allows for the creation of aarch64 wheels.

Furthermore, travis-ci.com provides access to Graviton2 instances which can be used as ARM64 build environments.
Travis-CI announcement: https://blog.travis-ci.com/2020-09-11-arm-on-aws

Is there any interest in ARM64 wheels? The main repo has recently added ARM64 CI support - https://github.com/scikit-learn/scikit-learn/pull/17996. Scipy recently released aarch64 wheels: https://pypi.org/project/scipy/#files

I've got a fork of this repo that uses Graviton2 to run the wheel build process. However, there are 19 FAILURE cases.
Build log: https://travis-ci.com/github/janaknat/scikit-learn-wheels/builds/191481236

Any suggestions?

**Comment by janaknat** [comment]
@glemaitre Any suggestion?

**Comment by adrinjalali** [comment]
I'd be happy to have an ARM64 wheel out. WDYT @ogrisel , would it make it to the coming release?

**Comment by ogrisel** [comment]
Sure :) We will need to upgrade our build CI infrastructure again. Maybe we could stream line it with https://github.com/joerick/cibuildwheel . I have not checked whether this would help of not.

**Comment by ogrisel** [comment]
> I've got a fork of this repo that uses Graviton2 to run the wheel build process. However, there are 19 FAILURE cases.
Build log: https://travis-ci.com/github/janaknat/scikit-learn-wheels/builds/191481236

@janaknat did you investigate if though failures are legit? It's weird because those tests do not fail on our own ARM CI:

https://travis-ci.org/github/scikit-learn/scikit-learn/jobs/739045599

There is only one failure (a doctest for LogisticRegression) that we would need to investigate.

Anyway if it's too long to solve them all I would not block the 0.24 release for this (at least not the first beta) but we can make a best effort to try to get it.

**Comment by rth** [comment]
> Maybe we could stream line it with joerick/cibuildwheel 

This was investigated in https://github.com/scikit-learn/scikit-learn/pull/17921

**Comment by janaknat** [comment]
@ogrisel I am using multibuild to build the wheels for Python 3.5, 3.6 and 3.7. Its a bit surprising that I'm hitting these failures. I am using arm64-graviton2 as the arch. I'll see if I get the same output in the main repo.

**Comment by ogrisel** [comment]
Closing in favor of scikit-learn/scikit-learn#18782.
